"""Public package entrypoint for depensee-tracker-client."""

from .contracts.auth import (
    AsanaAuthConfig,
    JiraAuthConfig,
    ProviderAuthConfig,
    YandexTrackerAuthConfig,
)
from .domain import (
    AuthenticationError,
    Comment,
    ConnectionDiagnostic,
    ConfigurationError,
    CreateCommentInput,
    CreateProjectInput,
    CreateRelationInput,
    CreateTaskInput,
    Project,
    Provider,
    ProviderCapabilityError,
    ProviderError,
    Relation,
    RelationType,
    Status,
    Task,
    TaskQuery,
    TrackerClientError,
    UpdateProjectInput,
    UpdateTaskInput,
    User,
    Workspace,
)
from .tracker_client import TrackerClient

TrackerKitError = TrackerClientError

__all__ = [
    "AsanaAuthConfig",
    "AuthenticationError",
    "Comment",
    "ConnectionDiagnostic",
    "ConfigurationError",
    "CreateCommentInput",
    "CreateProjectInput",
    "CreateRelationInput",
    "CreateTaskInput",
    "JiraAuthConfig",
    "Project",
    "Provider",
    "ProviderAuthConfig",
    "ProviderCapabilityError",
    "ProviderError",
    "Relation",
    "RelationType",
    "Status",
    "Task",
    "TaskQuery",
    "TrackerClient",
    "TrackerClientError",
    "TrackerKitError",
    "UpdateProjectInput",
    "UpdateTaskInput",
    "User",
    "Workspace",
    "YandexTrackerAuthConfig",
]
